# Generated by Django 4.1.13 on 2024-03-31 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=255)),
                ('Genero', models.CharField(blank=True, max_length=255, null=True)),
                ('Descripción', models.CharField(blank=True, max_length=255, null=True)),
                ('Desarrollador', models.CharField(blank=True, max_length=255, null=True)),
                ('Consola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LeonGames.consola')),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Marcas',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=255)),
                ('CorreoElectronico', models.CharField(max_length=255, unique=True)),
                ('Contraseña', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido_juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cantidad', models.IntegerField()),
                ('Juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LeonGames.juego')),
                ('Pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LeonGames.pedido')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='Comprador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comprador_pedidos', to='LeonGames.usuario'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='Juego',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LeonGames.juego'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='Vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendedor_pedidos', to='LeonGames.usuario'),
        ),
        migrations.AddField(
            model_name='juego',
            name='Marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LeonGames.marca'),
        ),
        migrations.AddField(
            model_name='juego',
            name='Usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LeonGames.usuario'),
        ),
        migrations.CreateModel(
            name='Comentarios_juegos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Texto', models.CharField(max_length=255)),
                ('Fecha', models.CharField(max_length=255)),
                ('Juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LeonGames.juego')),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LeonGames.usuario')),
            ],
        ),
    ]
