# Generated by Django 4.1.13 on 2024-04-20 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('LeonGames', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Fecha', models.DateField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='consola',
            options={'verbose_name_plural': 'Consolas'},
        ),
        migrations.RenameField(
            model_name='juego',
            old_name='Descripción',
            new_name='DescripciónJuego',
        ),
        migrations.RemoveField(
            model_name='juego',
            name='Consola',
        ),
        migrations.RemoveField(
            model_name='juego',
            name='Usuario',
        ),
        migrations.AddField(
            model_name='comentarios_juegos',
            name='DescripciónVenta',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='juego',
            name='Lanzamiento',
            field=models.IntegerField(default=2024),
        ),
        migrations.AlterField(
            model_name='comentarios_juegos',
            name='Usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='juego',
            name='Genero',
            field=models.CharField(choices=[('Acción', 'Acción'), ('Aventura', 'Aventura'), ('RPG', 'Rol (RPG)'), ('Disparos en primera persona', 'Disparos en primera persona (FPS)'), ('Disparos en tercera persona', 'Disparos en tercera persona (TPS)'), ('Plataforma', 'Plataforma'), ('Estrategia', 'Estrategia'), ('Simulación', 'Simulación'), ('Juego de cartas', 'Juego de cartas (Cartas)'), ('Estrategia en tiempo real', 'Estrategia en tiempo real (RTS)'), ('Horror', 'Horror'), ('Supervivencia', 'Supervivencia'), ('MMO', 'Multijugador masivo en línea (MMO)'), ('MOBA', 'Arena de batalla en línea multijugador (MOBA)'), ('Carreras', 'Carreras'), ('Lucha', 'Lucha'), ('Puzzle', 'Puzzle'), ('Novela visual', 'Novela visual (VN)'), ('Música', 'Música/Ritmo'), ('Deportes', 'Deportes'), ('Otro', 'Otro')], max_length=255),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='Comprador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comprador_pedidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='Vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendedor_pedidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.AddField(
            model_name='venta',
            name='Consola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LeonGames.consola'),
        ),
        migrations.AddField(
            model_name='venta',
            name='Juego',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LeonGames.juego'),
        ),
        migrations.AddField(
            model_name='venta',
            name='Usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='venta',
            name='Vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendedor_ventas', to=settings.AUTH_USER_MODEL),
        ),
    ]
