# Generated by Django 4.1.13 on 2024-04-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeonGames', '0003_rename_descripciónventa_comentarios_juegos_descripcionventa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentarios_juegos',
            name='DescripcionVenta',
        ),
        migrations.AddField(
            model_name='comentarios_juegos',
            name='Valoracion',
            field=models.IntegerField(blank=True, choices=[(1, '⭐'), (2, '⭐⭐'), (3, '⭐⭐⭐'), (4, '⭐⭐⭐⭐'), (5, '⭐⭐⭐⭐⭐')], null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='DescripcionVenta',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='comentarios_juegos',
            name='Fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='comentarios_juegos',
            name='Texto',
            field=models.TextField(blank=True, null=True),
        ),
    ]
