# Generated by Django 4.1.13 on 2024-04-21 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LeonGames', '0004_remove_comentarios_juegos_descripcionventa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='Usuario',
        ),
    ]
