# Generated by Django 4.1.13 on 2024-05-01 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LeonGames', '0005_remove_venta_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='Venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='LeonGames.venta'),
        ),
    ]
