# Generated by Django 4.1.13 on 2024-06-06 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeonGames', '0007_remove_pedido_venta_pedido_consola_pedido_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='Imagen',
            field=models.ImageField(blank=True, null=True, upload_to='ventas/'),
        ),
    ]
