# Generated by Django 4.1.13 on 2024-06-06 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeonGames', '0008_venta_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='Imagen',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
