# Generated by Django 4.1.13 on 2024-06-10 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('LeonGames', '0010_chat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='created_at',
            new_name='Fecha',
        ),
        migrations.RenameField(
            model_name='chat',
            old_name='message',
            new_name='Mensaje',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='response',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='user',
        ),
        migrations.AddField(
            model_name='chat',
            name='Usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chats', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
